### ISSUE TITLE
2.0.0 breaks build

### ISSUE THREAD

**Issue by Rehubbard** [bitrise-steplib/steps-change-value#15]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.0.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

After upgrading from 1.1.0 to 2.2.0, this build step no longer works. The file that it works with has not changed. It seems to be looking at an older version of the file for the value and it cannot find it. Very odd since 1.1.0 had no issues and the file hasn't been changed. Has anybody else had issues with 2.2.0?

We use this step twice in our React Native workflow. Once for Android and iOS. Its failing on the second run. Is this because its already change the file? If so how should we proceed?

Downgrading to 1.1.0 works and is the solution for us currently.

### Bitrise info

- Build URL: https://app.bitrise.io/build/5677a025-c300-41a4-9408-fda782563b2d#
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: Below in details

<details>
  <pre>
+------------------------------------------------------------------------------+
| (2) change-value@2                                                           |
+------------------------------------------------------------------------------+
| id: change-value                                                             |
| version: 2.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-10-13T14:18:30Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |

------------------------------------------
-------------OLD  FILE--------------------
------------------------------------------
import { Platform } from 'react-native'

export const SUPPORT_PHONE_NUMBER = '4159159076'
const devUrl =
  Platform.OS === 'android' ? 'http://10.0.2.2:3000' : 'http://localhost:3000'
// 'http://localhost:3000'
// 'https://hello-landing-staging.herokuapp.com'
export const BASE_URL = __DEV__ ? devUrl : 'https://hello-landing-staging.herokuapp.com'

------------------------------------------
2021/10/13 14:18:31 Provided old value (https://www.hellolanding.com) was not found in the file (./src/constants/constants.js)
|                                                                              |
  </pre>
</details>

**Comment by ofalvai** [comment]
Hey @Rehubbard 👋 
Are you sure that the step was working previously? I'm asking because in [version 2.0](https://github.com/bitrise-steplib/steps-change-value/releases/tag/2.0.0) a long-standing bug was fixed and it's possible that the (new) correct behavior breaks your workflow.

**Comment by Rehubbard** [comment]
Closing this issue. @ofalvai was correct. It wasn't working previously as I had first suspected.
