### ISSUE TITLE
Step as failed wrong value logic

### ISSUE THREAD

**Issue by rcholley** [bitrise-steplib/steps-change-value#6]
When adding a Change value step we are able to select if the step should failed or not if old value is not found:
"To mark a step as "Failed" if value for replacing isn't found." -> True or False
In my comprehension, if I want the step to fail I will choose True. But actullay setting true will not failed. To make it fail, we have to set to false. Doesn't sound logical.

I think instead of:
`inputIsFailIfOldValueNotFound = os.Getenv("notfound_exit") == "false"`
We should put:
`inputIsFailIfOldValueNotFound = os.Getenv("notfound_exit") == "true"`

Regards

**Comment by istx25** [comment]
Hi @rcholley,

Thank you for reaching out.

I have raised this with the tooling team to consider. They will decide if they want to merge the #7 pull request. Since there's an open pull request, I am going to close this issue.
